package Presentacion;

import Negocio.UtilesGraficos;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JComponent;
import javax.swing.JFrame;
import org.jfree.chart.ChartFrame;

/**
 *
 * @author Juan
 */
public final class DialogoValor extends javax.swing.JDialog {

    private JComponent Barra;
    private Dimension dimBarra = null;
    private UtilesGraficos utilesGraficos;
    private String nombreEmpresa;
    private JFrame frame;

    public void ocultarBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) internalFrame.getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }

    private void repintarGrafico(int num) {
        ChartFrame charFrame = utilesGraficos.dibujarGraficoLineas(frame, nombreEmpresa, num);

        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = charFrame.getSize();
        int width = (pantalla.width - ventana.width) / 2;
        int height = (pantalla.height - ventana.height) / 2;

        this.setTitle(nombreEmpresa.toUpperCase());
        this.lblNombre.setText(nombreEmpresa.toUpperCase());
        this.setBounds(width - this.getWidth() / 2, height, pantalla.width / 2, pantalla.height / 2);
        this.setSize((pantalla.width / 2 + pantalla.width / 4) + 30, pantalla.height / 2 + 90);
        this.internalFrame.setContentPane(charFrame.getContentPane());
        this.panel.setOpaque(true);
        this.panel.setBackground(new Color(204, 204, 204));
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public DialogoValor(java.awt.Frame parent, boolean modal, String nombreEmpresa, JFrame frame) {
        super(parent, modal);
        initComponents();

        this.nombreEmpresa = nombreEmpresa;
        this.frame = frame;

        utilesGraficos = new UtilesGraficos();
        utilesGraficos.renderTabla(tableMaxMin, false);
        utilesGraficos.renderTabla(tablaFichaValor, false);

        utilesGraficos.cargarTablarDialogoValor(this, nombreEmpresa);

        utilesGraficos.panelTransparente(panelOpciones);

        internalFrame.setBorder(null);

        JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) internalFrame.getUI()).getNorthPane();
        Dimension dimBarra = null;
        ocultarBarraTitulo();

        repintarGrafico(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFichaValor = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMaxMin = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        internalFrame = new javax.swing.JInternalFrame();
        panelOpciones = new javax.swing.JPanel();
        rbMes = new javax.swing.JRadioButton();
        rb6Meses = new javax.swing.JRadioButton();
        rbAnyo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        tablaFichaValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tablaFichaValor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ficha", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaFichaValor);

        tableMaxMin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableMaxMin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Máximo", "Mínimo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableMaxMin);

        lblNombre.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNombre.setText("Nombre empresa");

        internalFrame.setBorder(null);
        internalFrame.setVisible(true);

        javax.swing.GroupLayout internalFrameLayout = new javax.swing.GroupLayout(internalFrame.getContentPane());
        internalFrame.getContentPane().setLayout(internalFrameLayout);
        internalFrameLayout.setHorizontalGroup(
            internalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        internalFrameLayout.setVerticalGroup(
            internalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        rbMes.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rbMes);
        rbMes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbMes.setSelected(true);
        rbMes.setText("1 mes");
        rbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMesActionPerformed(evt);
            }
        });

        rb6Meses.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rb6Meses);
        rb6Meses.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rb6Meses.setText("6 meses");
        rb6Meses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6MesesActionPerformed(evt);
            }
        });

        rbAnyo.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rbAnyo);
        rbAnyo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbAnyo.setText("1 año");
        rbAnyo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAnyoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb6Meses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbAnyo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMes)
                    .addComponent(rb6Meses)
                    .addComponent(rbAnyo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblNombre)
                                .addGap(89, 89, 89))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(95, 95, 95))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(internalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblNombre)
                .addGap(27, 27, 27)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addComponent(internalFrame, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMesActionPerformed
        repintarGrafico(30);
    }//GEN-LAST:event_rbMesActionPerformed

    private void rb6MesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6MesesActionPerformed
        repintarGrafico(180);
    }//GEN-LAST:event_rb6MesesActionPerformed

    private void rbAnyoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAnyoActionPerformed
        repintarGrafico(365);
    }//GEN-LAST:event_rbAnyoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JInternalFrame internalFrame;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lblNombre;
    public static javax.swing.JPanel panel;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JRadioButton rb6Meses;
    private javax.swing.JRadioButton rbAnyo;
    private javax.swing.JRadioButton rbMes;
    public static javax.swing.JTable tablaFichaValor;
    public static javax.swing.JTable tableMaxMin;
    // End of variables declaration//GEN-END:variables
}
